### ISSUE TITLE
mid-function includes break compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by luastoned** [stealth/sshttp#7]
Basically you are doing `#include <linux/netfilter_ipv4.h>` right in the middle of `int dstaddr(int sock, sockaddr *dst, socklen_t dlen)` and the compiler does not seem happy about it.

    In file included from socket.cc:131:
    swab.h: In function 'int NS_Socket::dstaddr(int, sockaddr*, socklen_t)':
    swab.h:8:1: error: a function-definition is not allowed here before '{' token

**Comment by stealth** [comment]
solved by latest commits for both branches.
can you compile and verify it works on (was it Ubuntu 16.04?)

**Comment by luastoned** [comment]
Compile works on 16.04 now. Cheers.

**Comment by ZeroChaos-** [comment]
this is kind of a big deal, would you mind making a release with this fix?
